In [2]:
#sao separados os atributos 27-34, depois contabilizado quais subsequencias aparecem
import os
os.chdir('C:\\Users\\Usuario\\Desktop\\wallace\\UNILA\\DNA IC')

In [3]:
#sl sequencias
import splicenum as sp
a, b= sp.splicenum()
indices= range(27,35,1)
slseq=[]
for j in range(len(a)):
    vazio1=[]
    for i in range(len(indices)):
        v= a[j][indices[i]]
        vazio1.append(v)
    slseq.append(vazio1)
cdata= slseq
ctarg= b
cdata= cdata[0:1537]
quantidade = len(cdata)
while i < quantidade:
    b=cdata.count(cdata[i])
    if b>1:
        for j in range(b-1):
            cdata.remove(cdata[i])
        i= i
    else:
        i=i+1
    quantidade = len(cdata)

In [5]:
#tabela atributo valor - contagem
a, b= sp.splicenum()
AV=[]
for i in range(len(a)):
    vezes=[]
    a1= str(a[i])
    for j in range(len(cdata)):
        c1= str(cdata[j])
        c1= c1.replace('[','')
        c1= c1.replace(']','')
        c= a1.count(c1)
        vezes.append(c)
    AV.append(vezes)
print(AV)
        

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.


In [49]:
import numpy as np
from sklearn import svm
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import ShuffleSplit
from sklearn import tree
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import SGDClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier

In [48]:
clf=[]
nome=[]
clf.append(tree.DecisionTreeClassifier())
nome.append('Decision Tree')
clf.append(SVC(gamma='auto'))
nome.append('SVC Support Vector Machines')
clf.append(KNeighborsClassifier(n_neighbors=1))
nome.append('Nearest Neighbors1')
clf.append(GaussianNB())
nome.append('GaussianNB')
clf.append(MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1))
nome.append('MLP classifier')
for i in range(len(clf)):
    scores = cross_val_score(clf[i], AV, b, cv=10)
    y_pred = cross_val_predict(clf[i], AV, b, cv=10)
    conf_mat = confusion_matrix(b, y_pred)
    print(nome[i],'\nScores:',scores)
    print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
    print('Confusion:\n', conf_mat, '\n')

Decision Tree 
Scores: [0.615625   0.503125   0.628125   0.546875   0.628125   0.55172414
 0.5799373  0.53144654 0.56466877 0.65930599]
Accuracy: 0.58 (+/- 0.10) , ei: 0.54 , ie: 0.30, n: 0.73
Confusion:
 [[ 413   75  279]
 [  94  234  440]
 [ 144  304 1207]] 

SVC Support Vector Machines 
Scores: [0.51875    0.51875    0.51875    0.51875    0.51875    0.51724138
 0.51724138 0.51886792 0.52050473 0.52050473]
Accuracy: 0.52 (+/- 0.00) , ei: 0.00 , ie: 0.00, n: 1.00
Confusion:
 [[   0    0  767]
 [   0    0  768]
 [   0    0 1655]] 

Nearest Neighbors1 
Scores: [0.371875   0.33125    0.334375   0.3125     0.340625   0.3322884
 0.32288401 0.3081761  0.30599369 0.33438486]
Accuracy: 0.33 (+/- 0.04) , ei: 0.81 , ie: 0.40, n: 0.07
Confusion:
 [[ 625  108   34]
 [ 290  311  167]
 [1082  458  115]] 

GaussianNB 
Scores: [0.2875     0.296875   0.321875   0.3125     0.2875     0.27899687
 0.29467085 0.31132075 0.29652997 0.29968454]
Accuracy: 0.30 (+/- 0.02) , ei: 0.87 , ie: 0.11, n: 0.12
Confus

In [50]:
clf=tree.DecisionTreeClassifier()
clf= clf.fit(AV,b)
model = SelectFromModel(clf, prefit=True)
x = model.transform(AV)
print(len(AV[0]),len(x[0]))

414 122


In [51]:
clf=[]
nome=[]
cdata= x
ctarg= b
clf.append(tree.DecisionTreeClassifier())
nome.append('Decision Tree')
clf.append(SVC(gamma='auto'))
nome.append('SVC Support Vector Machines')
clf.append(KNeighborsClassifier(n_neighbors=1))
nome.append('Nearest Neighbors1')
clf.append(GaussianNB())
nome.append('GaussianNB')
clf.append(MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1))
nome.append('MLP classifier')
for i in range(len(clf)):
    scores = cross_val_score(clf[i], cdata, ctarg, cv=10)
    y_pred = cross_val_predict(clf[i], cdata, ctarg, cv=10)
    conf_mat = confusion_matrix(ctarg, y_pred)
    print(nome[i],'\nScores:',scores)
    print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
    print('Confusion:\n', conf_mat, '\n')

Decision Tree 
Scores: [0.678125   0.61875    0.684375   0.61875    0.7        0.58934169
 0.65830721 0.59748428 0.6340694  0.69400631]
Accuracy: 0.65 (+/- 0.08) , ei: 0.53 , ie: 0.23, n: 0.90
Confusion:
 [[ 409   36  322]
 [  50  175  543]
 [  81   92 1482]] 

SVC Support Vector Machines 
Scores: [0.51875    0.51875    0.51875    0.51875    0.51875    0.51724138
 0.51724138 0.51886792 0.52050473 0.52050473]
Accuracy: 0.52 (+/- 0.00) , ei: 0.00 , ie: 0.00, n: 1.00
Confusion:
 [[   0    0  767]
 [   0    0  768]
 [   0    0 1655]] 

Nearest Neighbors1 
Scores: [0.296875   0.30625    0.31875    0.271875   0.296875   0.28213166
 0.30721003 0.27044025 0.27129338 0.29022082]
Accuracy: 0.29 (+/- 0.03) , ei: 0.95 , ie: 0.23, n: 0.02
Confusion:
 [[ 727   29   11]
 [ 559  176   33]
 [1509  120   26]] 

GaussianNB 
Scores: [0.675      0.609375   0.678125   0.621875   0.703125   0.57366771
 0.64576803 0.60062893 0.64353312 0.68454259]
Accuracy: 0.64 (+/- 0.08) , ei: 0.53 , ie: 0.24, n: 0.88
Confu

In [18]:
cdata= cdata[0:1537]
quantidade = len(cdata)
while i < quantidade:
    b=cdata.count(cdata[i])
    if b>1:
        for j in range(b-1):
            cdata.remove(cdata[i])
        i= i
    else:
        i=i+1
    quantidade = len(cdata)
print(cdata)

[[2, 0, 1, 2, 3, 2, 0, 2], [1, 3, 3, 2, 3, 0, 0, 2], [0, 0, 1, 2, 3, 2, 0, 2], [2, 0, 3, 2, 3, 2, 1, 2], [2, 0, 2, 2, 3, 3, 0, 2], [0, 0, 0, 2, 3, 0, 0, 0], [0, 1, 2, 2, 3, 0, 0, 2], [0, 0, 2, 2, 3, 3, 1, 2], [3, 0, 3, 2, 3, 2, 0, 2], [1, 3, 2, 2, 3, 2, 1, 2], [2, 0, 2, 2, 3, 1, 0, 2], [2, 2, 0, 2, 3, 0, 0, 2], [0, 2, 2, 2, 3, 0, 2, 2], [1, 3, 0, 1, 0, 0, 1, 2], [2, 1, 2, 2, 3, 0, 3, 2], [3, 0, 2, 2, 3, 2, 3, 2], [0, 2, 3, 2, 3, 0, 1, 2], [2, 0, 2, 2, 3, 0, 0, 2], [0, 3, 2, 2, 3, 0, 2, 2], [0, 0, 2, 2, 3, 2, 2, 2], [1, 0, 2, 2, 3, 2, 1, 0], [1, 1, 2, 2, 3, 0, 0, 1], [2, 0, 2, 2, 3, 0, 2, 0], [1, 0, 0, 2, 3, 0, 0, 2], [1, 0, 2, 2, 3, 0, 0, 2], [2, 2, 2, 2, 3, 2, 0, 2], [2, 0, 2, 2, 3, 0, 0, 3], [0, 3, 2, 2, 3, 0, 3, 2], [2, 3, 2, 2, 3, 0, 0, 2], [0, 0, 2, 2, 3, 2, 3, 2], [2, 0, 2, 2, 3, 2, 0, 0], [0, 0, 2, 2, 3, 2, 1, 1], [0, 2, 2, 2, 3, 0, 1, 3], [2, 3, 2, 2, 3, 2, 0, 2], [3, 3, 3, 2, 3, 0, 0, 2], [3, 3, 2, 2, 3, 2, 2, 2], [3, 1, 0, 2, 3, 0, 0, 2], [3, 0, 2, 2, 3, 0, 0, 2], [2, 3, 2, 2

In [26]:
a= [[0,0],[99,9]]
a1= str(a[0])
b='0'
a1.count(b)

2

In [1]:
a=[0,0,0,0]
print(len(a))

4


In [ ]:
#sl sequencias
def sldata():
    import splicenum as sp
    a, b= sp.splicenum()
    indices= range(27,35,1)
    slseq=[]
    for j in range(len(a)):
        vazio1=[]
        for i in range(len(indices)):
            v= a[j][indices[i]]
            vazio1.append(v)
        slseq.append(vazio1)
    cdata= slseq
    ctarg= b
    cdata= cdata[0:1537]
    quantidade = len(cdata)
    while i < quantidade:
        b=cdata.count(cdata[i])
        if b>1:
            for j in range(b-1):
                cdata.remove(cdata[i])
            i= i
        else:
            i=i+1
        quantidade = len(cdata)
        #tabela atributo valor - contagem
    a, b= sp.splicenum()
    AV=[]
    for i in range(len(a)):
        vezes=[]
        a1= str(a[i])
        for j in range(len(cdata)):
            c1= str(cdata[j])
            c1= c1.replace('[','')
            c1= c1.replace(']','')
            c= a1.count(c1)
            vezes.append(c)
        AV.append(vezes)
    #print(len(AV))
    return AV , b