In [1]:
import os
os.chdir('C:\\Users\\Usuario\\Documents\\DNA---introns-exons-')

In [3]:
data1= open('splice.data', 'r')
f= data1.readlines()
for i in range(len(f)):
    f[i]= f[i].split(',')
for i in range(len(f)):
    del(f[i][1])
for i in range(len(f)):
    f[i][1]=f[i][1].split()[0]
c=[]
for i in range(len(f)):
    b=[]
    if f[i][0]=='EI':
        b.append(0)
    elif f[i][0]=='IE':
        b.append(1)
    elif f[i][0]=='N':
        b.append(2)
    a=[]
    for j in range(len(f[i][1])):
        if f[i][1][j]=='A':
            a.append(0)
        elif f[i][1][j]=='C':
            a.append(1)
        elif f[i][1][j]=='G':
            a.append(2)
        elif f[i][1][j]=='T':
            a.append(3)
        else:
            a.append(8)
    b.append(a)
    c.append(b)
cdata=[]
ctarg=[]

for i in range(len(c)):
    cdata.append(c[i][1])
    ctarg.append((c[i][0]))


[[1, 1, 0, 2, 1, 3, 2, 1, 0, 3, 1, 0, 1, 0, 2, 2, 0, 2, 2, 1, 1, 0, 2, 1, 2, 0, 2, 1, 0, 2, 2, 3, 1, 3, 2, 3, 3, 1, 1, 0, 0, 2, 2, 2, 1, 1, 3, 3, 1, 2, 0, 2, 1, 1, 0, 2, 3, 1, 3, 2], [0, 2, 0, 1, 1, 1, 2, 1, 1, 2, 2, 2, 0, 2, 2, 1, 2, 2, 0, 2, 2, 0, 1, 1, 3, 2, 1, 0, 2, 2, 2, 3, 2, 0, 2, 1, 1, 1, 1, 0, 1, 1, 2, 1, 1, 1, 1, 3, 1, 1, 2, 3, 2, 1, 1, 1, 1, 1, 2, 1], [2, 0, 2, 2, 3, 2, 0, 0, 2, 2, 0, 1, 2, 3, 1, 1, 3, 3, 1, 1, 1, 1, 0, 2, 2, 0, 2, 1, 1, 2, 2, 3, 2, 0, 2, 0, 0, 2, 1, 2, 1, 0, 2, 3, 1, 2, 2, 2, 2, 2, 1, 0, 1, 2, 2, 2, 2, 0, 3, 2], [2, 2, 2, 1, 3, 2, 1, 2, 3, 3, 2, 1, 3, 2, 2, 3, 1, 0, 1, 0, 3, 3, 1, 1, 3, 2, 2, 1, 0, 2, 2, 3, 0, 3, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 3, 3, 2, 1, 3, 1, 2, 2, 3, 3, 3, 3, 1, 1, 1, 1], [2, 1, 3, 1, 0, 2, 1, 1, 1, 1, 1, 0, 2, 2, 3, 1, 0, 1, 1, 1, 0, 2, 2, 0, 0, 1, 3, 2, 0, 1, 2, 3, 2, 0, 2, 3, 2, 3, 1, 1, 1, 1, 0, 3, 1, 1, 1, 2, 2, 1, 1, 1, 3, 3, 2, 0, 1, 1, 1, 3], [1, 0, 2, 0, 1, 3, 2, 2, 2, 3, 2, 2, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 3, 3, 1, 0, 2, 1, 2

In [16]:
#CFS base
import splicenum as sp
a, b= sp.splicenum()
indices= [29, 31, 28, 30, 34, 27, 32, 33, 24, 22]
CFSdata=[]
for j in range(len(a)):
    vazio1=[]
    for i in range(len(indices)):
        v= a[j][indices[i]]
        vazio1.append(v)
    CFSdata.append(vazio1)
cdata= CFSdata
ctarg= b

In [2]:
#CFS base
import splicenum as sp
a, b= sp.splicenum()
print(len(a), len(b))

3190 3190


In [3]:
print(a[0])

[1, 1, 0, 2, 1, 3, 2, 1, 0, 3, 1, 0, 1, 0, 2, 2, 0, 2, 2, 1, 1, 0, 2, 1, 2, 0, 2, 1, 0, 2, 2, 3, 1, 3, 2, 3, 3, 1, 1, 0, 0, 2, 2, 2, 1, 1, 3, 3, 1, 2, 0, 2, 1, 1, 0, 2, 3, 1, 3, 2]


In [17]:
import numpy as np
from sklearn import svm
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import ShuffleSplit
from sklearn import tree
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import cross_val_predict
from sklearn.linear_model import SGDClassifier
from sklearn.gaussian_process import GaussianProcessClassifier

In [8]:
clf=[]
nome=[]
clf.append(tree.DecisionTreeClassifier(criterion= 'entropy'))
nome.append('Decision Tree entro')
for i in range(len(clf)):
    scores = cross_val_score(clf[i], cdata, ctarg, cv=10)
    y_pred = cross_val_predict(clf[i], cdata, ctarg, cv=10)
    conf_mat = confusion_matrix(ctarg, y_pred)
    print(nome[i],'\nScores:',scores)
    print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
    print('Confusion:\n', conf_mat, '\n')

Decision Tree entro 
Scores: [0.9125     0.896875   0.9        0.884375   0.928125   0.88401254
 0.90909091 0.89622642 0.89589905 0.90851735]
Accuracy: 0.90 (+/- 0.03) , ei: 0.91 , ie: 0.84, n: 0.93
Confusion:
 [[ 695   35   37]
 [  43  644   81]
 [  37   72 1546]] 



In [18]:
clf=[]
nome=[]
clf.append(tree.DecisionTreeClassifier())
nome.append('Decision Tree')
clf.append(SVC(gamma='auto'))
nome.append('SVC Support Vector Machines')
clf.append(KNeighborsClassifier(n_neighbors=1))
nome.append('Nearest Neighbors1')
clf.append(KNeighborsClassifier(n_neighbors=3))
nome.append('Nearest Neighbors3')
clf.append(GaussianNB())
nome.append('GaussianNB')
clf.append(MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1))
nome.append('MLP classifier')
clf.append(SGDClassifier(loss="hinge", penalty="l2", max_iter=5, tol= None))
nome.append('SGDclassifier - Stochastic Gradient Descent')
for i in range(len(clf)):
    scores = cross_val_score(clf[i], cdata, ctarg, cv=10)
    y_pred = cross_val_predict(clf[i], cdata, ctarg, cv=10)
    conf_mat = confusion_matrix(ctarg, y_pred)
    print(nome[i],'\nScores:',scores)
    print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
    print('Confusion:\n', conf_mat, '\n')

Decision Tree 
Scores: [0.909375   0.91875    0.93125    0.903125   0.9125     0.89028213
 0.92476489 0.88679245 0.88328076 0.94637224]
Accuracy: 0.91 (+/- 0.04) , ei: 0.92 , ie: 0.83, n: 0.93
Confusion:
 [[ 705   35   27]
 [  44  641   83]
 [  34   74 1547]] 

SVC Support Vector Machines 
Scores: [0.909375   0.896875   0.884375   0.878125   0.9125     0.88087774
 0.9153605  0.8836478  0.88328076 0.87381703]
Accuracy: 0.89 (+/- 0.03) , ei: 0.93 , ie: 0.88, n: 0.88
Confusion:
 [[ 714   27   26]
 [  64  675   29]
 [  51  148 1456]] 

Nearest Neighbors1 
Scores: [0.88125    0.83125    0.8625     0.821875   0.875      0.84639498
 0.87147335 0.85534591 0.82018927 0.86119874]
Accuracy: 0.85 (+/- 0.04) , ei: 0.88 , ie: 0.88, n: 0.82
Confusion:
 [[ 676   62   29]
 [  34  679   55]
 [ 102  188 1365]] 

Nearest Neighbors3 
Scores: [0.853125   0.859375   0.86875    0.834375   0.875      0.82445141
 0.84952978 0.86792453 0.80126183 0.84227129]
Accuracy: 0.85 (+/- 0.04) , ei: 0.89 , ie: 0.89, n: 0.

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDC

SGDclassifier - Stochastic Gradient Descent 
Scores: [0.740625   0.775      0.73125    0.815625   0.71875    0.78683386
 0.86206897 0.77987421 0.7318612  0.69716088]
Accuracy: 0.76 (+/- 0.09) , ei: 0.71 , ie: 0.59, n: 0.84
Confusion:
 [[ 546   62  159]
 [ 108  454  206]
 [ 126  146 1383]] 



C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDC

In [3]:
data2= open('splice.data.txt', 'r')
f= data2.readlines()
for i in range(len(f)):
    f[i]= f[i].split(',')
for i in range(len(f)):
    del(f[i][1])
for i in range(len(f)):
    f[i][1]=f[i][1].split()[0]
c=[]
for i in range(len(f)):
    b=[]
    if f[i][0]=='EI':
        b.append(0)
    elif f[i][0]=='IE':
        b.append(1)
    elif f[i][0]=='N':
        b.append(2)
    a=[]
    l=0
    for j in range(len(f[i][1])):
        if f[i][1][j]=='A':
            l= l-1
            a.append(l)
        elif f[i][1][j]=='C':
            l= l-2
            a.append(l)
        elif f[i][1][j]=='G':
            l= l+1
            a.append(l)
        elif f[i][1][j]=='T':
            l= l+2
            a.append(l)
        else:
            a.append(l)
    b.append(a)
    c.append(b)
cdata=[]
ctarg=[]

for i in range(len(c)):
    cdata.append(c[i][1])
    ctarg.append((c[i][0]))



In [ ]:
clf = svm.SVC(kernel='linear', C=1)
scores = cross_val_score(clf, cdata, ctarg, cv=10)
print(scores)

In [24]:
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
y_pred = cross_val_predict(clf[0], cdata, ctarg, cv=10)
conf_mat = confusion_matrix(ctarg, y_pred)
print(conf_mat)

[[ 681   42   44]
 [  41  641   86]
 [  48   77 1530]]


In [38]:
print(cdata[0])

[-2, -4, -5, -4, -6, -4, -3, -5, -6, -4, -6, -7, -9, -10, -9, -8, -9, -8, -7, -9, -11, -12, -11, -13, -12, -13, -12, -14, -15, -14, -13, -11, -13, -11, -10, -8, -6, -8, -10, -11, -12, -11, -10, -9, -11, -13, -11, -9, -11, -10, -11, -10, -12, -14, -15, -14, -12, -14, -12, -11]


In [6]:
a=[[1,1,1],[2,2,2]]
print(sum(a[0]))

3


In [1]:
def splicenum():
    data1= open('splice.data.txt', 'r')
    f= data1.readlines()
    for i in range(len(f)):
        f[i]= f[i].split(',')
    for i in range(len(f)):
        del(f[i][1])
    for i in range(len(f)):
        f[i][1]=f[i][1].split()[0]
    c=[]
    for i in range(len(f)):
        b=[]
        if f[i][0]=='EI':
            b.append(0)
        elif f[i][0]=='IE':
            b.append(1)
        elif f[i][0]=='N':
            b.append(2)
        a=[]
        for j in range(len(f[i][1])):
            if f[i][1][j]=='A':
                a.append(0)
            elif f[i][1][j]=='C':
                a.append(1)
            elif f[i][1][j]=='G':
                a.append(2)
            elif f[i][1][j]=='T':
                a.append(3)
            else:
                a.append(8)
        b.append(a)
        c.append(b)
    cdata=[]
    ctarg=[]

    for i in range(len(c)):
        cdata.append(c[i][1])
        ctarg.append((c[i][0]))
    return cdata , ctarg

In [4]:
#recurrence plot on dataset
import numpy as np # linear algebra
from scipy.spatial.distance import pdist, squareform #scipy spatial distance
import sklearn as sk
import sklearn.metrics.pairwise
#função para passar os dados para imgem já com flatten()
def recurrence(d):
    def recurrence_plot(s, eps=None, steps=None):
        if eps==None: eps=0.1
        if steps==None: steps=10
        d = sk.metrics.pairwise.pairwise_distances(s)
        d = np.floor(d / eps)
        d[d > steps] = steps
        #Z = squareform(d)
        return d
    data=[]
    for i in range(len(d)):
        a= d[i]
        a= np.asarray(a)
        a= a.reshape(-1, 1)
        a= recurrence_plot(a)
        a=a.flatten()
        data.append(a)
    return data
#import splicenum as sp
#a, b= sp.splicenum()
cdata= recurrence(cdata)
#ctarg= b

In [6]:
print(1np.e - 3)

SyntaxError: invalid syntax (<ipython-input-6-c1be0956e483>, line 1)

In [13]:
#CFS base
import splicenum as sp
a, b= sp.splicenum()
indices= [29, 31, 28, 30, 34, 27, 32, 33, 24, 22]
CFSdata=[]
for j in range(len(a)):
    vazio1=[]
    for i in range(len(indices)):
        v= a[j][indices[i]]
        vazio1.append(v)
    CFSdata.append(vazio1)
cdata= CFSdata
ctarg= b

In [14]:
cdata= CFSdata
ctarg= b

In [ ]:
import skfeature
import skfeature.function.information_theoretical_based.FCBF
a= fcbf(cdata,ctarg)
