In [1]:
import os
os.chdir('C:\\Users\\Usuario\\Desktop\\wallace\\UNILA\\DNA IC')

In [4]:
#recurrence plot on dataset
import numpy as np # linear algebra
from scipy.spatial.distance import pdist, squareform #scipy spatial distance
import sklearn as sk
import sklearn.metrics.pairwise
#função para passar os dados para imgem já com flatten()
def recurrence(d):
    def recurrence_plot(s, eps=None, steps=None):
        if eps==None: eps=0.1
        if steps==None: steps=10
        d = sk.metrics.pairwise.pairwise_distances(s)
        d = np.floor(d / eps)
        d[d > steps] = steps
        #Z = squareform(d)
        return d
    data=[]
    for i in range(len(d)):
        a= d[i]
        a= np.asarray(a)
        a= a.reshape(-1, 1)
        a= recurrence_plot(a)
        a=a.flatten()
        data.append(a)
    return data
#import splicenum as sp
#a, b= sp.splicenum()
cdata= recurrence(cdata)
#ctarg= b

In [2]:
#CFS base
import splicenum as sp
a, b= sp.splicenum()
indices= [29, 31, 28, 30, 34, 27, 32, 33, 24, 22]
CFSdata=[]
for j in range(len(a)):
    vazio1=[]
    for i in range(len(indices)):
        v= a[j][indices[i]]
        vazio1.append(v)
    CFSdata.append(vazio1)
cdata= CFSdata
ctarg= b

In [2]:
#dataset
data1= open('splice.data.txt', 'r')
f= data1.readlines()
for i in range(len(f)):
    f[i]= f[i].split(',')
for i in range(len(f)):
    del(f[i][1])
for i in range(len(f)):
    f[i][1]=f[i][1].split()[0]
c=[]
for i in range(len(f)):
    b=[]
    if f[i][0]=='EI':
        b.append(0)
    elif f[i][0]=='IE':
        b.append(1)
    elif f[i][0]=='N':
        b.append(2)
    a=[]
    for j in range(len(f[i][1])):
        if f[i][1][j]=='A':
            a.append(0)
        elif f[i][1][j]=='C':
            a.append(1)
        elif f[i][1][j]=='G':
            a.append(2)
        elif f[i][1][j]=='T':
            a.append(3)
        else:
            a.append(8)
    b.append(a)
    c.append(b)
cdata=[]
ctarg=[]

for i in range(len(c)):
    cdata.append(c[i][1])
    ctarg.append((c[i][0]))

In [4]:
import numpy as np
from sklearn import svm
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import ShuffleSplit
from sklearn import tree
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import cross_val_predict
from sklearn.linear_model import SGDClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier

In [5]:
clf=[]
nome=[]

clf.append(tree.DecisionTreeClassifier())
nome.append('Decision Tree')
clf.append(SVC(gamma='auto'))
nome.append('SVC Support Vector Machines')
clf.append(KNeighborsClassifier(n_neighbors=1))
nome.append('Nearest Neighbors1')
clf.append(GaussianNB())
nome.append('GaussianNB')
clf.append(MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1))
nome.append('MLP classifier')
clf.append(SGDClassifier(loss="hinge", penalty="l2", max_iter=5, tol= None))
nome.append('SGDclassifier - Stochastic Gradient Descent')
print('BAGGING')
for i in range(len(clf)):
    bclf = BaggingClassifier(clf[i], max_samples=0.5, max_features=0.5)
    scores = cross_val_score(bclf, cdata, ctarg, cv=10)
    y_pred = cross_val_predict(bclf, cdata, ctarg, cv=10)
    conf_mat = confusion_matrix(ctarg, y_pred)
    print(nome[i],'\nScores:',scores)
    print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
    print('Confusion:\n', conf_mat, '\n')




BAGGING
Decision Tree 
Scores: [0.921875   0.875      0.940625   0.90625    0.96875    0.89968652
 0.9184953  0.88993711 0.90851735 0.91167192]
Accuracy: 0.91 (+/- 0.05) , ei: 0.92 , ie: 0.83, n: 0.96
Confusion:
 [[ 705   25   37]
 [  41  639   88]
 [  30   44 1581]] 

SVC Support Vector Machines 
Scores: [0.9        0.903125   0.896875   0.88125    0.934375   0.89341693
 0.9153605  0.89622642 0.87697161 0.92429022]
Accuracy: 0.90 (+/- 0.03) , ei: 0.93 , ie: 0.77, n: 0.92
Confusion:
 [[ 715   19   33]
 [ 109  595   64]
 [  63   72 1520]] 

Nearest Neighbors2 
Scores: [0.93125    0.90625    0.94375    0.909375   0.90625    0.88714734
 0.93103448 0.89622642 0.93059937 0.91798107]
Accuracy: 0.92 (+/- 0.03) , ei: 0.93 , ie: 0.89, n: 0.92
Confusion:
 [[ 713   28   26]
 [  41  680   47]
 [  53   72 1530]] 

Nearest Neighbors3 
Scores: [0.884375   0.940625   0.93125    0.90625    0.925      0.88087774
 0.90282132 0.89622642 0.91798107 0.92113565]
Accuracy: 0.91 (+/- 0.04) , ei: 0.91 , ie: 0.8

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDC

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDC

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDC

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDC

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDC

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDC

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDC

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDC

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDC

SGDclassifier - Stochastic Gradient Descent 
Scores: [0.7125     0.60625    0.725      0.571875   0.678125   0.67084639
 0.64890282 0.7672956  0.65615142 0.72239748]
Accuracy: 0.68 (+/- 0.11) , ei: 0.59 , ie: 0.40, n: 0.87
Confusion:
 [[ 449   66  252]
 [  75  306  387]
 [  93  117 1445]] 



C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDC

In [6]:
print('random Forest')
clf = RandomForestClassifier(n_estimators=10)
scores = cross_val_score(clf, cdata, ctarg, cv=10)
y_pred = cross_val_predict(clf, cdata, ctarg, cv=10)
conf_mat = confusion_matrix(ctarg, y_pred)
print('\nScores:',scores)
print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
print('Confusion:\n', conf_mat, '\n')

random Forest

Scores: [0.940625   0.93125    0.940625   0.934375   0.953125   0.91222571
 0.93730408 0.9245283  0.92744479 0.95583596]
Accuracy: 0.94 (+/- 0.02) , ei: 0.93 , ie: 0.89, n: 0.94
Confusion:
 [[ 716   22   29]
 [  41  687   40]
 [  29   66 1560]] 



In [7]:
print('AdaBoost')
clf = AdaBoostClassifier(n_estimators=100)
scores = cross_val_score(clf, cdata, ctarg, cv=10)
y_pred = cross_val_predict(clf, cdata, ctarg, cv=10)
conf_mat = confusion_matrix(ctarg, y_pred)
print('\nScores:',scores)
print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
print('Confusion:\n', conf_mat, '\n')

AdaBoost

Scores: [0.90625    0.93125    0.9        0.89375    0.903125   0.84952978
 0.9153605  0.92138365 0.88328076 0.92429022]
Accuracy: 0.90 (+/- 0.05) , ei: 0.96 , ie: 0.89, n: 0.89
Confusion:
 [[ 733   23   11]
 [  26  682   60]
 [  88  102 1465]] 



In [8]:
print('Gradient Tree Boosting')
clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0)
scores = cross_val_score(clf, cdata, ctarg, cv=10)
y_pred = cross_val_predict(clf, cdata, ctarg, cv=10)
conf_mat = confusion_matrix(ctarg, y_pred)
print('\nScores:',scores)
print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
print('Confusion:\n', conf_mat, '\n')

Gradient Tree Boosting

Scores: [0.9625     0.95       0.965625   0.940625   0.978125   0.93730408
 0.95924765 0.94339623 0.94952681 0.96214511]
Accuracy: 0.95 (+/- 0.02) , ei: 0.96 , ie: 0.94, n: 0.96
Confusion:
 [[ 739   18   10]
 [  27  720   21]
 [  21   47 1587]] 



In [9]:
print('Voting Classifier')
clf1 = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0)
clf2 = AdaBoostClassifier(n_estimators=100)
clf3 = tree.DecisionTreeClassifier()
clf4 = GaussianNB()
clf5 = SVC(gamma='auto')


clf = VotingClassifier(estimators=[('gbc', clf1), ('ada', clf2), ('DTc', clf3), ('gNB', clf4), ('svc', clf5)], voting='hard')
scores = cross_val_score(clf, cdata, ctarg, cv=10)
y_pred = cross_val_predict(clf, cdata, ctarg, cv=10)
conf_mat = confusion_matrix(ctarg, y_pred)
print('\nScores:',scores)
print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
print('Confusion:\n', conf_mat, '\n')

Voting Classifier

Scores: [0.95       0.95       0.934375   0.91875    0.9625     0.93103448
 0.94670846 0.93710692 0.93690852 0.95583596]
Accuracy: 0.94 (+/- 0.02) , ei: 0.96 , ie: 0.95, n: 0.93
Confusion:
 [[ 735   23    9]
 [  25  731   12]
 [  34   78 1543]] 



###### data2= open('splice.data.txt', 'r')
f= data2.readlines()
for i in range(len(f)):
    f[i]= f[i].split(',')
for i in range(len(f)):
    del(f[i][1])
for i in range(len(f)):
    f[i][1]=f[i][1].split()[0]
c=[]
for i in range(len(f)):
    b=[]
    if f[i][0]=='EI':
        b.append(0)
    elif f[i][0]=='IE':
        b.append(1)
    elif f[i][0]=='N':
        b.append(2)
    a=[]
    l=0
    for j in range(len(f[i][1])):
        if f[i][1][j]=='A':
            l= l-1
            a.append(l)
        elif f[i][1][j]=='C':
            l= l-2
            a.append(l)
        elif f[i][1][j]=='G':
            l= l+1
            a.append(l)
        elif f[i][1][j]=='T':
            l= l+2
            a.append(l)
        else:
            a.append(l)
    b.append(a)
    c.append(b)
cdata=[]
ctarg=[]

for i in range(len(c)):
    cdata.append(c[i][1])
    ctarg.append((c[i][0]))



In [ ]:
import numpy as np
from sklearn import svm
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import ShuffleSplit
from sklearn import tree
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import cross_val_predict
from sklearn.linear_model import SGDClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier

#bagging
clf=[]
nome=[]
clf.append(tree.DecisionTreeClassifier())
nome.append('Decision Tree')
clf.append(SVC(gamma= 'scale'))
nome.append('SVC Support Vector Machines')
clf.append(KNeighborsClassifier(n_neighbors=2))
nome.append('Nearest Neighbors2')
clf.append(KNeighborsClassifier(n_neighbors=3))
nome.append('Nearest Neighbors3')
clf.append(KNeighborsClassifier(n_neighbors=4))
nome.append('Nearest Neighbors4')
clf.append(KNeighborsClassifier(n_neighbors=5))
nome.append('Nearest Neighbors5')
clf.append(GaussianNB())
nome.append('GaussianNB')
clf.append(MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1))
nome.append('MLP classifier')
clf.append(SGDClassifier(loss="hinge", penalty="l2", max_iter=5))
nome.append('SGDclassifier - Stochastic Gradient Descent')
print('BAGGING')
for i in range(len(clf)):
    bclf = BaggingClassifier(clf[i], max_samples=0.5, max_features=0.5)
    scores = cross_val_score(bclf, cdata, ctarg, cv=10)
    y_pred = cross_val_predict(bclf, cdata, ctarg, cv=10)
    conf_mat = confusion_matrix(ctarg, y_pred)
    print(nome[i],'\nScores:',scores)
    print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
    print('Confusion:\n', conf_mat, '\n')

print('random Forest')
clf = RandomForestClassifier(n_estimators=10)
scores = cross_val_score(clf, cdata, ctarg, cv=10)
y_pred = cross_val_predict(clf, cdata, ctarg, cv=10)
conf_mat = confusion_matrix(ctarg, y_pred)
print('\nScores:',scores)
print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
print('Confusion:\n', conf_mat, '\n')

print('AdaBoost')
clf = AdaBoostClassifier(n_estimators=100)
scores = cross_val_score(clf, cdata, ctarg, cv=10)
y_pred = cross_val_predict(clf, cdata, ctarg, cv=10)
conf_mat = confusion_matrix(ctarg, y_pred)
print('\nScores:',scores)
print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
print('Confusion:\n', conf_mat, '\n')

print('Gradient Tree Boosting')
clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0)
scores = cross_val_score(clf, cdata, ctarg, cv=10)
y_pred = cross_val_predict(clf, cdata, ctarg, cv=10)
conf_mat = confusion_matrix(ctarg, y_pred)
print('\nScores:',scores)
print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
print('Confusion:\n', conf_mat, '\n')

print('Voting Classifier')
clf1 = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0)
clf2 = AdaBoostClassifier(n_estimators=100)
clf3 = tree.DecisionTreeClassifier()
clf4 = GaussianNB()
clf5 = SVC(gamma='scale')


clf = VotingClassifier(estimators=[('gbc', clf1), ('ada', clf2), ('DTc', clf3), ('gNB', clf4), ('svc', clf5)], voting='hard')
scores = cross_val_score(clf, cdata, ctarg, cv=10)
y_pred = cross_val_predict(clf, cdata, ctarg, cv=10)
conf_mat = confusion_matrix(ctarg, y_pred)
print('\nScores:',scores)
print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
print('Confusion:\n', conf_mat, '\n')

BAGGING
Decision Tree 
Scores: [0.81875    0.759375   0.78125    0.690625   0.81875    0.76802508
 0.75862069 0.70440252 0.73817035 0.76025237]
Accuracy: 0.76 (+/- 0.08) , ei: 0.67 , ie: 0.70, n: 0.82
Confusion:
 [[ 517   90  160]
 [  70  539  159]
 [ 104  202 1349]] 

SVC Support Vector Machines 
Scores: [0.578125   0.54375    0.596875   0.571875   0.553125   0.52978056
 0.64890282 0.54402516 0.53943218 0.57728707]
Accuracy: 0.57 (+/- 0.07) , ei: 0.08 , ie: 0.15, n: 0.99
Confusion:
 [[  59    2  706]
 [   0  119  649]
 [   1   11 1643]] 

Nearest Neighbors2 
Scores: [0.546875   0.51875    0.565625   0.534375   0.55625    0.51410658
 0.56739812 0.52515723 0.52681388 0.60567823]
Accuracy: 0.55 (+/- 0.05) , ei: 0.04 , ie: 0.10, n: 1.00
Confusion:
 [[  33    0  734]
 [   0   74  694]
 [   1    6 1648]] 

Nearest Neighbors3 
Scores: [0.54375    0.51875    0.54375    0.5375     0.58125    0.51724138
 0.52978056 0.52201258 0.52050473 0.55835962]
Accuracy: 0.54 (+/- 0.04) , ei: 0.03 , ie: 0.0

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDC

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDC

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDC

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDC

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDC

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDC

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDC

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDC

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDC

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDC

SGDclassifier - Stochastic Gradient Descent 
Scores: [0.59375    0.65       0.565625   0.61875    0.709375   0.58934169
 0.62695925 0.58805031 0.57413249 0.70977918]
Accuracy: 0.62 (+/- 0.10) , ei: 0.30 , ie: 0.34, n: 0.89
Confusion:
 [[ 229   59  479]
 [  80  261  427]
 [  75  102 1478]] 

random Forest

Scores: [0.690625   0.653125   0.709375   0.6125     0.771875   0.67398119
 0.70219436 0.65408805 0.65615142 0.70977918]
Accuracy: 0.68 (+/- 0.08) , ei: 0.51 , ie: 0.52, n: 0.82
Confusion:
 [[ 393   74  300]
 [  52  397  319]
 [ 127  170 1358]] 

AdaBoost

Scores: [0.75       0.725      0.734375   0.675      0.76875    0.69592476
 0.7492163  0.6918239  0.72555205 0.79495268]
Accuracy: 0.73 (+/- 0.07) , ei: 0.69 , ie: 0.73, n: 0.75
Confusion:
 [[ 529   87  151]
 [  63  559  146]
 [ 191  220 1244]] 

Gradient Tree Boosting

Scores: [0.753125   0.765625   0.79375    0.715625   0.825      0.7523511
 0.78683386 0.74842767 0.76340694 0.79495268]
Accuracy: 0.77 (+/- 0.06) , ei: 0.69 , ie: 0.