In [1]:
import os
os.chdir('C:\\Users\\Usuario\\Desktop\\wallace\\UNILA\\DNA IC')

In [2]:
data1= open('splice.data.txt', 'r')
f= data1.readlines()
for i in range(len(f)):
    f[i]= f[i].split(',')
for i in range(len(f)):
    del(f[i][1])
for i in range(len(f)):
    f[i][1]=f[i][1].split()[0]
c=[]
for i in range(len(f)):
    b=[]
    if f[i][0]=='EI':
        b.append(0)
    elif f[i][0]=='IE':
        b.append(1)
    elif f[i][0]=='N':
        b.append(2)
    a=[]
    for j in range(len(f[i][1])):
        if f[i][1][j]=='A':
            a.append(0)
        elif f[i][1][j]=='C':
            a.append(1)
        elif f[i][1][j]=='G':
            a.append(2)
        elif f[i][1][j]=='T':
            a.append(3)
        else:
            a.append(8)
    b.append(a)
    c.append(b)
cdata=[]
ctarg=[]

for i in range(len(c)):
    cdata.append(c[i][1])
    ctarg.append((c[i][0]))

In [3]:
import numpy as np
from sklearn import svm
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import ShuffleSplit
from sklearn import tree
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import SGDClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier

In [4]:
clf=tree.DecisionTreeClassifier()
clf= clf.fit(cdata,ctarg)
model = SelectFromModel(clf, prefit=True)
x = model.transform(cdata)
print(len(cdata[0]),len(x[0]))

60 8


In [22]:
from abc import ABCMeta, abstractmethod
from warnings import warn

import numpy as np
from scipy.sparse import issparse, csc_matrix

from sklearn.base import TransformerMixin
from sklearn.utils import check_array, safe_mask
from sklearn.feature_selection import base as h
h.SelectorMixin(x)
a= get_support(model.transform(cdata), indices=False)

TypeError: object() takes no parameters

In [5]:
print('Voting Classifier')
cdata= x
clf1 = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0)
clf2 = AdaBoostClassifier(n_estimators=100)
clf3 = tree.DecisionTreeClassifier()
clf4 = GaussianNB()
clf5 = SVC()


clf = VotingClassifier(estimators=[('gbc', clf1), ('ada', clf2), ('DTc', clf3), ('gNB', clf4), ('svc', clf5)], voting='hard')
scores = cross_val_score(clf, cdata, ctarg, cv=10)
y_pred = cross_val_predict(clf, cdata, ctarg, cv=10)
conf_mat = confusion_matrix(ctarg, y_pred)
print('\nScores:',scores)
print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
print('Confusion:\n', conf_mat, '\n')

Voting Classifier


C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: Fut


Scores: [0.946875   0.940625   0.9375     0.91875    0.95625    0.92476489
 0.95297806 0.91823899 0.94321767 0.94637224]
Accuracy: 0.94 (+/- 0.03) , ei: 0.95 , ie: 0.95, n: 0.93
Confusion:
 [[ 727   28   12]
 [  25  729   14]
 [  37   81 1537]] 



In [5]:
clf=[]
nome=[]
clf.append(tree.DecisionTreeClassifier())
nome.append('Decision Tree')
clf.append(SVC(gamma='auto'))
nome.append('SVC Support Vector Machines')
clf.append(KNeighborsClassifier(n_neighbors=1))
nome.append('Nearest Neighbors2')
clf.append(GaussianNB())
nome.append('GaussianNB')
clf.append(MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1))
nome.append('MLP classifier')
clf.append(SGDClassifier(loss="hinge", penalty="l2", max_iter=5))
nome.append('SGDclassifier - Stochastic Gradient Descent')
for i in range(len(clf)):
    scores = cross_val_score(clf[i], x, ctarg, cv=10)
    y_pred = cross_val_predict(clf[i], x, ctarg, cv=10)
    conf_mat = confusion_matrix(ctarg, y_pred)
    print(nome[i],'\nScores:',scores)
    print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
    print('Confusion:\n', conf_mat, '\n')

Decision Tree 
Scores: [0.940625   0.90625    0.9        0.934375   0.9375     0.92476489
 0.93730408 0.8836478  0.9022082  0.93690852]
Accuracy: 0.92 (+/- 0.04) , ei: 0.93 , ie: 0.89, n: 0.93
Confusion:
 [[ 712   23   32]
 [  34  682   52]
 [  45   75 1535]] 

SVC Support Vector Machines 
Scores: [0.925      0.9        0.9125     0.884375   0.9125     0.89655172
 0.93103448 0.89937107 0.88643533 0.89589905]
Accuracy: 0.90 (+/- 0.03) , ei: 0.93 , ie: 0.91, n: 0.89
Confusion:
 [[ 717   24   26]
 [  58  696   14]
 [  41  142 1472]] 

Nearest Neighbors2 
Scores: [0.903125   0.865625   0.85       0.871875   0.896875   0.85579937
 0.89655172 0.87735849 0.84858044 0.87381703]
Accuracy: 0.87 (+/- 0.04) , ei: 0.87 , ie: 0.89, n: 0.87
Confusion:
 [[ 669   74   24]
 [  29  684   55]
 [  70  150 1435]] 

GaussianNB 
Scores: [0.859375   0.909375   0.8875     0.871875   0.921875   0.86206897
 0.89028213 0.88679245 0.87381703 0.87697161]
Accuracy: 0.88 (+/- 0.04) , ei: 0.78 , ie: 0.98, n: 0.89
Confu

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDC

SGDclassifier - Stochastic Gradient Descent 
Scores: [0.590625   0.721875   0.76875    0.5875     0.821875   0.79623824
 0.78996865 0.68867925 0.76025237 0.78233438]
Accuracy: 0.73 (+/- 0.16) , ei: 0.66 , ie: 0.58, n: 0.81
Confusion:
 [[ 510   82  175]
 [  87  444  237]
 [ 129  181 1345]] 



C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


In [7]:
clf=[]
nome=[]
clf.append(KNeighborsClassifier(n_neighbors=1, metric= 'hamming'))
nome.append('Nearest Neighbors1 - hamming')
clf.append(KNeighborsClassifier(n_neighbors=3, metric= 'hamming'))
nome.append('Nearest Neighbors3 - hamming')
clf.append(KNeighborsClassifier(n_neighbors=5, metric= 'hamming'))
nome.append('Nearest Neighbors5 - hamming')
for i in range(len(clf)):
    scores = cross_val_score(clf[i], x, ctarg, cv=10)
    y_pred = cross_val_predict(clf[i], x, ctarg, cv=10)
    conf_mat = confusion_matrix(ctarg, y_pred)
    print(nome[i],'\nScores:',scores)
    print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
    print('Confusion:\n', conf_mat, '\n')

Nearest Neighbors1 - hamming 
Scores: [0.89375    0.85625    0.859375   0.828125   0.89375    0.87774295
 0.87460815 0.86163522 0.84858044 0.88643533]
Accuracy: 0.87 (+/- 0.04) , ei: 0.88 , ie: 0.90, n: 0.85
Confusion:
 [[ 675   76   16]
 [  32  688   48]
 [  71  178 1406]] 

Nearest Neighbors3 - hamming 
Scores: [0.8875     0.875      0.875      0.86875    0.9        0.87147335
 0.87774295 0.88050314 0.86750789 0.88012618]
Accuracy: 0.88 (+/- 0.02) , ei: 0.93 , ie: 0.93, n: 0.83
Confusion:
 [[ 710   48    9]
 [  34  718   16]
 [  96  185 1374]] 

Nearest Neighbors5 - hamming 
Scores: [0.88125    0.865625   0.878125   0.884375   0.875      0.86833856
 0.88714734 0.88050314 0.84542587 0.87381703]
Accuracy: 0.87 (+/- 0.02) , ei: 0.94 , ie: 0.94, n: 0.82
Confusion:
 [[ 720   41    6]
 [  41  719    8]
 [ 103  203 1349]] 

