In [1]:
import os
os.chdir('C:\\Users\\Usuario\\Desktop\\wallace\\UNILA\\DNA IC')

In [4]:
#recurrence plot
import numpy as np # linear algebra
from scipy.spatial.distance import pdist, squareform #scipy spatial distance
import sklearn as sk
import sklearn.metrics.pairwise
#função para passar os dados para imgem já com flatten()
def recurrence(d):
    def recurrence_plot(s, eps=None, steps=None):
        if eps==None: eps=0.1
        if steps==None: steps=10
        d = sk.metrics.pairwise.pairwise_distances(s)
        d = np.floor(d / eps)
        d[d > steps] = steps
        #Z = squareform(d)
        return d
    data=[]
    for i in range(len(d)):
        a= d[i]
        a= np.asarray(a)
        a= a.reshape(-1, 1)
        a= recurrence_plot(a)
        a=a.flatten()
        data.append(a)
    return data
#import splicenum as sp
#a, b= sp.splicenum()
cdata= recurrence(cdata)


In [2]:
#CFS base
import splicenum as sp
a, b= sp.splicenum()
indices= [29, 31, 28, 30, 34, 27, 32, 33, 24, 22]
CFSdata=[]
for j in range(len(a)):
    vazio1=[]
    for i in range(len(indices)):
        v= a[j][indices[i]]
        vazio1.append(v)
    CFSdata.append(vazio1)
cdata= CFSdata
ctarg= b

In [24]:
print(len(cdata[0]))

3600


In [2]:
data1= open('splice.data.txt', 'r')
f= data1.readlines()
for i in range(len(f)):
    f[i]= f[i].split(',')
for i in range(len(f)):
    del(f[i][1])
for i in range(len(f)):
    f[i][1]=f[i][1].split()[0]
c=[]
for i in range(len(f)):
    b=[]
    if f[i][0]=='EI':
        b.append(0)
    elif f[i][0]=='IE':
        b.append(1)
    elif f[i][0]=='N':
        b.append(2)
    a=[]
    for j in range(len(f[i][1])):
        if f[i][1][j]=='A':
            a.append(0)
        elif f[i][1][j]=='C':
            a.append(1)
        elif f[i][1][j]=='G':
            a.append(2)
        elif f[i][1][j]=='T':
            a.append(3)
        else:
            a.append(8)
    b.append(a)
    c.append(b)
cdata=[]
ctarg=[]

for i in range(len(c)):
    cdata.append(c[i][1])
    ctarg.append((c[i][0]))

In [3]:
import numpy as np
import sklearn
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import cross_val_predict

In [25]:
clf=[]
nome=[]
clf.append(KNeighborsClassifier(n_neighbors=3, metric= 'euclidean'))
nome.append('Nearest Neighbors3 - euclidean')
clf.append(KNeighborsClassifier(n_neighbors=3, metric= 'manhattan'))
nome.append('Nearest Neighbors3 - manhattan')
clf.append(KNeighborsClassifier(n_neighbors=3, metric= 'chebyshev'))
nome.append('Nearest Neighbors3 - chebyshev')
clf.append(KNeighborsClassifier(n_neighbors=3, metric= 'minkowski'))
nome.append('Nearest Neighbors3 - minkowski')
clf.append(KNeighborsClassifier(n_neighbors=3, metric= 'wminkowski'))
nome.append('Nearest Neighbors3 - wminkowski')
clf.append(KNeighborsClassifier(n_neighbors=3, metric= 'seuclidean'))
nome.append('Nearest Neighbors3 - seuclidean')
clf.append(KNeighborsClassifier(n_neighbors=3, metric= 'mahalanobis'))
nome.append('Nearest Neighbors3 - mahalanobis')
clf.append(KNeighborsClassifier(n_neighbors=3, metric= 'hamming'))
nome.append('Nearest Neighbors3 - minkowski')
clf.append(KNeighborsClassifier(n_neighbors=3, metric= 'canberra'))
nome.append('Nearest Neighbors3 - minkowski')
clf.append(KNeighborsClassifier(n_neighbors=3, metric= 'braycurtis'))
nome.append('Nearest Neighbors3 - minkowski')
for i in range(len(clf)):
    scores = cross_val_score(clf[i], cdata, ctarg, cv=10)
    y_pred = cross_val_predict(clf[i], cdata, ctarg, cv=10)
    conf_mat = confusion_matrix(ctarg, y_pred)
    print(nome[i],'\nScores:',scores)
    print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
    print('Confusion:\n', conf_mat, '\n')

Nearest Neighbors3 - euclidean 
Scores: [0.6625     0.625      0.6        0.60625    0.6        0.56426332
 0.62695925 0.61006289 0.60883281 0.62776025]
Accuracy: 0.61 (+/- 0.05) , ei: 0.64 , ie: 0.58, n: 0.62
Confusion:
 [[ 491   71  205]
 [ 137  447  184]
 [ 378  259 1018]] 



KeyboardInterrupt: 

In [4]:
clf=[]
nome=[]
o= sorted(sklearn.neighbors.VALID_METRICS['brute'])
for i in range(len(o)):
    clf.append(KNeighborsClassifier(n_neighbors=1, metric= o[i]))
    nome.append('Nearest Neighbors1 - '+ o[i])
for i in range(len(clf)):
    try:
        scores = cross_val_score(clf[i], cdata, ctarg, cv=10)
        y_pred = cross_val_predict(clf[i], cdata, ctarg, cv=10)
        conf_mat = confusion_matrix(ctarg, y_pred)
        print(nome[i],'\nScores:',scores)
        print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
        print('Confusion:\n', conf_mat, '\n')
    except Exception:
        pass
   

Nearest Neighbors3 - braycurtis 
Scores: [0.865625   0.840625   0.85       0.834375   0.8875     0.85266458
 0.86520376 0.85534591 0.83596215 0.87697161]
Accuracy: 0.86 (+/- 0.03) , ei: 0.91 , ie: 0.87, n: 0.83
Confusion:
 [[ 695   51   21]
 [  48  671   49]
 [ 100  189 1366]] 

Nearest Neighbors3 - canberra 
Scores: [0.853125   0.834375   0.85625    0.84375    0.88125    0.85893417
 0.85266458 0.82389937 0.829653   0.85173502]
Accuracy: 0.85 (+/- 0.03) , ei: 0.89 , ie: 0.84, n: 0.83
Confusion:
 [[ 680   46   41]
 [  53  648   67]
 [ 141  135 1379]] 

Nearest Neighbors3 - chebyshev 
Scores: [0.746875   0.715625   0.75625    0.66875    0.771875   0.73354232
 0.66144201 0.71069182 0.67192429 0.65615142]
Accuracy: 0.71 (+/- 0.08) , ei: 0.49 , ie: 0.69, n: 0.82
Confusion:
 [[ 378  197  192]
 [  13  532  223]
 [  57  245 1353]] 

Nearest Neighbors3 - cityblock 
Scores: [0.890625   0.85       0.875      0.83125    0.8875     0.84952978
 0.87460815 0.85534591 0.83911672 0.88958991]
Accuracy: 

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:542: FutureWarning: From version 0.22, errors during fit will result in a cross validation score of NaN by default. Use error_score='raise' if you want an exception raised or error_score=np.nan to adopt the behavior from version 0.22.
  FutureWarning)


Nearest Neighbors3 - manhattan 
Scores: [0.890625   0.85       0.875      0.83125    0.8875     0.84952978
 0.87460815 0.85534591 0.83911672 0.88958991]
Accuracy: 0.86 (+/- 0.04) , ei: 0.90 , ie: 0.90, n: 0.83
Confusion:
 [[ 687   61   19]
 [  33  692   43]
 [  93  184 1378]] 

Nearest Neighbors3 - matching 
Scores: [0.7125     0.675      0.690625   0.725      0.75625    0.72100313
 0.68652038 0.69811321 0.68454259 0.7192429 ]
Accuracy: 0.71 (+/- 0.05) , ei: 0.20 , ie: 0.87, n: 0.87
Confusion:
 [[ 155  271  341]
 [   9  667   92]
 [  28  194 1433]] 

Nearest Neighbors3 - minkowski 
Scores: [0.88125    0.83125    0.8625     0.821875   0.875      0.84639498
 0.87147335 0.85534591 0.82018927 0.86119874]
Accuracy: 0.85 (+/- 0.04) , ei: 0.88 , ie: 0.88, n: 0.82
Confusion:
 [[ 676   62   29]
 [  34  679   55]
 [ 102  188 1365]] 

Nearest Neighbors3 - rogerstanimoto 
Scores: [0.7125     0.675      0.690625   0.725      0.75625    0.72100313
 0.68652038 0.69811321 0.68454259 0.7192429 ]
Accura

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:542: FutureWarning: From version 0.22, errors during fit will result in a cross validation score of NaN by default. Use error_score='raise' if you want an exception raised or error_score=np.nan to adopt the behavior from version 0.22.
  FutureWarning)


Nearest Neighbors3 - sokalmichener 
Scores: [0.7125     0.675      0.690625   0.725      0.75625    0.72100313
 0.68652038 0.69811321 0.68454259 0.7192429 ]
Accuracy: 0.71 (+/- 0.05) , ei: 0.20 , ie: 0.87, n: 0.87
Confusion:
 [[ 155  271  341]
 [   9  667   92]
 [  28  194 1433]] 

Nearest Neighbors3 - sokalsneath 
Scores: [0.715625   0.678125   0.690625   0.725      0.75625    0.72100313
 0.69278997 0.69811321 0.67823344 0.7192429 ]
Accuracy: 0.71 (+/- 0.05) , ei: 0.20 , ie: 0.87, n: 0.87
Confusion:
 [[ 155  271  341]
 [   9  668   91]
 [  32  189 1434]] 

Nearest Neighbors3 - sqeuclidean 
Scores: [0.83125    0.809375   0.809375   0.8125     0.859375   0.80877743
 0.830721   0.8081761  0.80126183 0.82018927]
Accuracy: 0.82 (+/- 0.03) , ei: 0.95 , ie: 0.82, n: 0.76
Confusion:
 [[ 728   20   19]
 [  98  632   38]
 [ 172  230 1253]] 



C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:542: FutureWarning: From version 0.22, errors during fit will result in a cross validation score of NaN by default. Use error_score='raise' if you want an exception raised or error_score=np.nan to adopt the behavior from version 0.22.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to bool by check_pairwise_arrays.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to bool by check_pairwise_arrays.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to bool by check_pairwise_arrays.
  warnings.warn(msg, DataConversionWarning)
C

Nearest Neighbors3 - yule 
Scores: [0.24375    0.253125   0.25625    0.2625     0.25625    0.2539185
 0.2539185  0.24528302 0.24921136 0.24290221]
Accuracy: 0.25 (+/- 0.01) , ei: 1.00 , ie: 0.00, n: 0.02
Confusion:
 [[ 767    0    0]
 [ 768    0    0]
 [1541   78   36]] 



C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to bool by check_pairwise_arrays.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to bool by check_pairwise_arrays.
  warnings.warn(msg, DataConversionWarning)


In [ ]:
clf=[]
nome=[]
clf.append(KNeighborsClassifier(n_neighbors=3, metric='wminkowski', metric_params={'w': 1}))
nome.append('Nearest Neighbors3 - wminkowski')
for i in range(len(clf)):
    scores = cross_val_score(clf[i], cdata, ctarg, cv=10)
    y_pred = cross_val_predict(clf[i], cdata, ctarg, cv=10)
    conf_mat = confusion_matrix(ctarg, y_pred)
    print(nome[i],'\nScores:',scores)
    print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
    print('Confusion:\n', conf_mat, '\n')

In [13]:
sorted(sklearn.neighbors.VALID_METRICS['brute'])

['braycurtis',
 'canberra',
 'chebyshev',
 'cityblock',
 'correlation',
 'cosine',
 'cosine',
 'dice',
 'euclidean',
 'hamming',
 'jaccard',
 'kulsinski',
 'l1',
 'l2',
 'mahalanobis',
 'manhattan',
 'matching',
 'minkowski',
 'precomputed',
 'rogerstanimoto',
 'russellrao',
 'seuclidean',
 'sokalmichener',
 'sokalsneath',
 'sqeuclidean',
 'wminkowski',
 'yule']

In [11]:
print(str(o[0]))

braycurtis


In [17]:
clf=[]
nome=[]
clf.append(KNeighborsClassifier(n_neighbors=1, metric= 'hamming'))
nome.append('Nearest Neighbors1 - hamming')
clf.append(KNeighborsClassifier(n_neighbors=5, metric= 'hamming'))
nome.append('Nearest Neighbors5 - hamming')
clf.append(KNeighborsClassifier(n_neighbors=10, metric= 'hamming'))
nome.append('Nearest Neighbors10 - hamming')
for i in range(len(clf)):
    scores = cross_val_score(clf[i], cdata, ctarg, cv=10)
    y_pred = cross_val_predict(clf[i], cdata, ctarg, cv=10)
    conf_mat = confusion_matrix(ctarg, y_pred)
    print(nome[i],'\nScores:',scores)
    print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
    print('Confusion:\n', conf_mat, '\n')

Nearest Neighbors1 - hamming 
Scores: [0.765625   0.76875    0.69375    0.71875    0.8125     0.73040752
 0.73040752 0.70440252 0.67192429 0.74763407]
Accuracy: 0.73 (+/- 0.08) , ei: 0.84 , ie: 0.82, n: 0.64
Confusion:
 [[ 647   57   63]
 [  78  631   59]
 [ 314  276 1065]] 

Nearest Neighbors5 - hamming 
Scores: [0.7625     0.80625    0.75625    0.775      0.825      0.80877743
 0.77115987 0.77672956 0.72239748 0.78864353]
Accuracy: 0.78 (+/- 0.06) , ei: 0.93 , ie: 0.91, n: 0.65
Confusion:
 [[ 710   40   17]
 [  58  698   12]
 [ 336  241 1078]] 

Nearest Neighbors10 - hamming 
Scores: [0.81875    0.828125   0.828125   0.79375    0.8625     0.84639498
 0.81818182 0.77987421 0.76656151 0.82334385]
Accuracy: 0.82 (+/- 0.06) , ei: 0.93 , ie: 0.94, n: 0.71
Confusion:
 [[ 717   39   11]
 [  43  720    5]
 [ 268  219 1168]] 



In [3]:
data2= open('splice.data.txt', 'r')
f= data2.readlines()
for i in range(len(f)):
    f[i]= f[i].split(',')
for i in range(len(f)):
    del(f[i][1])
for i in range(len(f)):
    f[i][1]=f[i][1].split()[0]
c=[]
for i in range(len(f)):
    b=[]
    if f[i][0]=='EI':
        b.append(0)
    elif f[i][0]=='IE':
        b.append(1)
    elif f[i][0]=='N':
        b.append(2)
    a=[]
    l=0
    for j in range(len(f[i][1])):
        if f[i][1][j]=='A':
            l= l-1
            a.append(l)
        elif f[i][1][j]=='C':
            l= l-2
            a.append(l)
        elif f[i][1][j]=='G':
            l= l+1
            a.append(l)
        elif f[i][1][j]=='T':
            l= l+2
            a.append(l)
        else:
            a.append(l)
    b.append(a)
    c.append(b)
cdata=[]
ctarg=[]

for i in range(len(c)):
    cdata.append(c[i][1])
    ctarg.append((c[i][0]))



In [4]:
clf=[]
nome=[]
o= sorted(sklearn.neighbors.VALID_METRICS['brute'])
for i in range(len(o)):
    clf.append(KNeighborsClassifier(n_neighbors=3, metric= o[i]))
    nome.append('Nearest Neighbors3 - '+ o[i])
for i in range(len(clf)):
    try:
        scores = cross_val_score(clf[i], cdata, ctarg, cv=10)
        y_pred = cross_val_predict(clf[i], cdata, ctarg, cv=10)
        conf_mat = confusion_matrix(ctarg, y_pred)
        print(nome[i],'\nScores:',scores)
        print("Accuracy: %0.2f (+/- %0.2f) , ei: %0.2f , ie: %0.2f, n: %0.2f" % (scores.mean(), scores.std() * 2, conf_mat[0][0]/sum(conf_mat[0]), conf_mat[1][1]/sum(conf_mat[1]),conf_mat[2][2]/sum(conf_mat[2])))
        print('Confusion:\n', conf_mat, '\n')
    except Exception:
        pass
 

Nearest Neighbors3 - braycurtis 
Scores: [0.4875     0.4875     0.509375   0.484375   0.5        0.53918495
 0.51724138 0.51886792 0.52365931 0.56466877]
Accuracy: 0.51 (+/- 0.05) , ei: 0.54 , ie: 0.31, n: 0.60
Confusion:
 [[414  61 292]
 [156 237 375]
 [415 254 986]] 

Nearest Neighbors3 - canberra 
Scores: [0.4625     0.525      0.534375   0.453125   0.53125    0.52978056
 0.56112853 0.52201258 0.46056782 0.50473186]
Accuracy: 0.51 (+/- 0.07) , ei: 0.51 , ie: 0.32, n: 0.59
Confusion:
 [[395  63 309]
 [161 248 359]
 [433 243 979]] 

Nearest Neighbors3 - chebyshev 
Scores: [0.490625   0.44375    0.5625     0.478125   0.484375   0.52351097
 0.53605016 0.52201258 0.47634069 0.5362776 ]
Accuracy: 0.51 (+/- 0.07) , ei: 0.51 , ie: 0.31, n: 0.59
Confusion:
 [[393  67 307]
 [161 239 368]
 [449 226 980]] 

Nearest Neighbors3 - cityblock 
Scores: [0.528125   0.50625    0.55625    0.48125    0.53125    0.54231975
 0.53918495 0.53773585 0.50157729 0.52681388]
Accuracy: 0.53 (+/- 0.04) , ei: 0.56 

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:542: FutureWarning: From version 0.22, errors during fit will result in a cross validation score of NaN by default. Use error_score='raise' if you want an exception raised or error_score=np.nan to adopt the behavior from version 0.22.
  FutureWarning)


Nearest Neighbors3 - manhattan 
Scores: [0.528125   0.50625    0.55625    0.48125    0.53125    0.54231975
 0.53918495 0.53773585 0.50157729 0.52681388]
Accuracy: 0.53 (+/- 0.04) , ei: 0.56 , ie: 0.30, n: 0.61
Confusion:
 [[ 429   62  276]
 [ 151  232  385]
 [ 406  235 1014]] 

Nearest Neighbors3 - matching 
Scores: [0.4125     0.384375   0.425      0.390625   0.4625     0.46081505
 0.4137931  0.38679245 0.34700315 0.41009464]
Accuracy: 0.41 (+/- 0.07) , ei: 0.28 , ie: 0.38, n: 0.48
Confusion:
 [[218 219 330]
 [141 291 336]
 [344 514 797]] 

Nearest Neighbors3 - minkowski 
Scores: [0.48125    0.49375    0.553125   0.465625   0.51875    0.53605016
 0.48902821 0.50628931 0.50157729 0.5362776 ]
Accuracy: 0.51 (+/- 0.05) , ei: 0.53 , ie: 0.29, n: 0.60
Confusion:
 [[407  66 294]
 [141 226 401]
 [428 239 988]] 

Nearest Neighbors3 - rogerstanimoto 
Scores: [0.4125     0.384375   0.425      0.390625   0.4625     0.46081505
 0.4137931  0.38679245 0.34700315 0.41009464]
Accuracy: 0.41 (+/- 0.07

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:542: FutureWarning: From version 0.22, errors during fit will result in a cross validation score of NaN by default. Use error_score='raise' if you want an exception raised or error_score=np.nan to adopt the behavior from version 0.22.
  FutureWarning)


Nearest Neighbors3 - sokalmichener 
Scores: [0.4125     0.384375   0.425      0.390625   0.4625     0.46081505
 0.4137931  0.38679245 0.34700315 0.41009464]
Accuracy: 0.41 (+/- 0.07) , ei: 0.28 , ie: 0.38, n: 0.48
Confusion:
 [[218 219 330]
 [141 291 336]
 [344 514 797]] 

Nearest Neighbors3 - sokalsneath 
Scores: [0.41875    0.396875   0.41875    0.390625   0.4625     0.47335423
 0.40752351 0.39937107 0.35646688 0.42902208]
Accuracy: 0.42 (+/- 0.06) , ei: 0.29 , ie: 0.39, n: 0.48
Confusion:
 [[225 217 325]
 [136 298 334]
 [347 506 802]] 

Nearest Neighbors3 - sqeuclidean 
Scores: [0.48125    0.496875   0.553125   0.465625   0.51875    0.53291536
 0.48902821 0.50628931 0.50473186 0.5362776 ]
Accuracy: 0.51 (+/- 0.05) , ei: 0.53 , ie: 0.29, n: 0.60
Confusion:
 [[409  66 292]
 [141 226 401]
 [428 240 987]] 



C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:542: FutureWarning: From version 0.22, errors during fit will result in a cross validation score of NaN by default. Use error_score='raise' if you want an exception raised or error_score=np.nan to adopt the behavior from version 0.22.
  FutureWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to bool by check_pairwise_arrays.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to bool by check_pairwise_arrays.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to bool by check_pairwise_arrays.
  warnings.warn(msg, DataConversionWarning)
C

C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to bool by check_pairwise_arrays.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to bool by check_pairwise_arrays.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to bool by check_pairwise_arrays.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Usuario\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to bool by check_pairwise_arrays.
  warnings.warn(msg, DataConversionWarning)


Nearest Neighbors3 - yule 
Scores: [0.24375    0.24375    0.25       0.24375    0.240625   0.24137931
 0.24451411 0.24213836 0.24605678 0.23974763]
Accuracy: 0.24 (+/- 0.01) , ei: 1.00 , ie: 0.00, n: 0.01
Confusion:
 [[ 766    0    1]
 [ 764    2    2]
 [1634   12    9]] 



In [15]:
import splicenum as sp
a, b= sp.splicenum()
print(a)


[[1, 1, 0, 2, 1, 3, 2, 1, 0, 3, 1, 0, 1, 0, 2, 2, 0, 2, 2, 1, 1, 0, 2, 1, 2, 0, 2, 1, 0, 2, 2, 3, 1, 3, 2, 3, 3, 1, 1, 0, 0, 2, 2, 2, 1, 1, 3, 3, 1, 2, 0, 2, 1, 1, 0, 2, 3, 1, 3, 2], [0, 2, 0, 1, 1, 1, 2, 1, 1, 2, 2, 2, 0, 2, 2, 1, 2, 2, 0, 2, 2, 0, 1, 1, 3, 2, 1, 0, 2, 2, 2, 3, 2, 0, 2, 1, 1, 1, 1, 0, 1, 1, 2, 1, 1, 1, 1, 3, 1, 1, 2, 3, 2, 1, 1, 1, 1, 1, 2, 1], [2, 0, 2, 2, 3, 2, 0, 0, 2, 2, 0, 1, 2, 3, 1, 1, 3, 3, 1, 1, 1, 1, 0, 2, 2, 0, 2, 1, 1, 2, 2, 3, 2, 0, 2, 0, 0, 2, 1, 2, 1, 0, 2, 3, 1, 2, 2, 2, 2, 2, 1, 0, 1, 2, 2, 2, 2, 0, 3, 2], [2, 2, 2, 1, 3, 2, 1, 2, 3, 3, 2, 1, 3, 2, 2, 3, 1, 0, 1, 0, 3, 3, 1, 1, 3, 2, 2, 1, 0, 2, 2, 3, 0, 3, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 3, 3, 2, 1, 3, 1, 2, 2, 3, 3, 3, 3, 1, 1, 1, 1], [2, 1, 3, 1, 0, 2, 1, 1, 1, 1, 1, 0, 2, 2, 3, 1, 0, 1, 1, 1, 0, 2, 2, 0, 0, 1, 3, 2, 0, 1, 2, 3, 2, 0, 2, 3, 2, 3, 1, 1, 1, 1, 0, 3, 1, 1, 1, 2, 2, 1, 1, 1, 3, 3, 2, 0, 1, 1, 1, 3], [1, 0, 2, 0, 1, 3, 2, 2, 2, 3, 2, 2, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 3, 3, 1, 0, 2, 1, 2

In [16]:
import recurrence as rp
import numpy as np # linear algebra
from scipy.spatial.distance import pdist, squareform #scipy spatial distance
import sklearn as sk
import sklearn.metrics.pairwise
cdata= rp.recurrence(a)
print(cdata)

ERROR:root:
UnicodeDecodeError while processing traceback.



NameError: name 'np' is not defined